#
# Example pair.io config.  
# https://github.com/zkim/pairio-config-example
#

# Quickstarts are pre-packaged instances, which allow you to get up
# and running in a short amount of time.  Pair.io will examine your
# repo and try to pick the correct one.
#
# You can force a particular quickstart like so:
#quickstart: empty # | ruby19 | rails3 | nodejs | clojure

# Pair.io gives you fine-grained control over what we provision for
# you. Here's the full set of config options:

image-id: ami-1aad5273 # must be in the us-east-1 region
size: large # | micro | small
inbound-ports: 
  - 22  # Make sure you've got 22 so pair can connect
        # to your instance.
  - 80
  - 81
  - "tcp:1.2.3.4/32:443"
  - "udp:0.0.0.0/0:1234"
provision: chef # none | chef | pallet | puppet (working on it)

# when chef (http://wiki.opscode.com/display/chef/Chef+Solo)
chef:
  config: solo.rb # chef-solo -c flag
  json-attributes: node.json # -j flag
# recipe-url: http://example.com/chef-solo.tar.gz # -r flag



