#
# Lee's pair.io config.  
#

# image-id: ami-cef405a7
size: large # | micro | small | large
inbound-ports: 
  - 22
  - 80
  - 81

provision: none # none | sh | chef

pairio-image: 4e25dd75e4b07ad9855ad3bb-dakrone-zkim/pairio-config-example

