#
# Lee's pair.io config.  
#

# image-id: ami-cef405a7
size: large # | micro | small | large
inbound-ports: 
  - 22
  - 80
  - 81

provision: none # none | sh | chef

pairio-image: 4e2ecf75e4b05e4b71ad6d8f-dakrone-dakrone/pairio-config

