#
# Lee's pair.io config.  
#

# image-id: ami-cef405a7
size: large # | micro | small | large
inbound-ports: 
  - 22
  - 80
  - 81
  - 9200
  - 9201
  - 4005
  - udp:0.0.0.0/0:61234
  - udp:0.0.0.0/0:62345
  - udp:0.0.0.0/0:61111
  - udp:0.0.0.0/0:62222
  - udp:0.0.0.0/0:63333
  - udp:0.0.0.0/0:64444

provision: none # none | sh | chef

pairio-image: 4e47bd8ce4b04aa28253e316-dakrone-dakrone/pairio-config

